### ISSUE TITLE
Support for virtual systems

### ISSUE THREAD

**Issue by alvagante** [puppetlabs/puppetlabs-panos#116]
## Use Case
Module does not seem to work on devices where [virtual systems](https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-admin/virtual-systems/virtual-systems-overview) are used.

## Describe the Solution You Would Like
The ability to specify the virtual system name (vsys1, vsys2 ...), for each resource type who has not global only usage and which can be applied to single virtual systems .

## Describe Alternatives You've Considered
Haven't found any way to workaround the issue, when a resource like panos_address is used on a device with virtual systems an error as the following is returned:
```
Notice: /Stage[main]/Profile::Paloalto/Panos_address[sg1nwa012]/ensure: defined 'ensure' as 'present' (corrective)
Error: panos_address[sg1nwa012]: Creating: Failed after 0.151279 seconds: Received "error" with code 8: Object not unique: For commands that operate on a single object, the specified object is not unique.
<response status='error' code='8'>
  <msg>
    Path doesn't uniquely identify an object
  </msg>
</response>
Error: /Stage[main]/Profile::Paloalto/Panos_address[sg1nwa012]: Could not evaluate: Execution encountered an error
```

## Additional Context
Have to implement the module where Virtual systems are in place.

**Comment by DavidS** [comment]
See also https://tickets.puppetlabs.com/browse/MODULES-10385

**Comment by pmcmaw** [comment]
Resolving as this is being tracked on https://tickets.puppetlabs.com/browse/MODULES-10385 and will avoid duplication. Work effort has been carried out, however there seems to be a struggle to get verification that it works as expected.
